package org.solutions.q0389;

/*
    389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

 */

import java.util.HashMap;
import java.util.Map;

public class FindTheDifference {

    /* FIRST SOLUTION THOUGHT

    public char findTheDifference(String s, String t) {

        Map<Character, Integer> freq = new HashMap<>();

        // Adding all elements of t to the map;
        for (char c : t.toCharArray()) {
            freq.put(c, freq.getOrDefault(c, 0) + 1);
        }

        // Removing all s elements
        for (char c : s.toCharArray()) {
            freq.put(c, freq.get(c) - 1);
            if (freq.get(c) == 0) {
                freq.remove(c);
            }
        }
        // The one that remains was added;
        return freq.entrySet().stream().findFirst().get().getKey();
    } */

    // SECOND SOLUTION - simpler - based o ASCII code
    public char findTheDifference(String s, String t) {

        // Creates an accumulator
        int sum = 0;
        // Sum all the char of t
        for (char c : t.toCharArray()) {
            sum += c;
        }
        // Subtract all the char of s
        for (char c : s.toCharArray()){
            sum -= c;
        }
        // Convert the remaining value to char
        return (char) sum;
    }
}

/**
 * Intuition
 * Since t contains all characters from s plus one additional character (in any order),
 * the sum of ASCII values of all characters in t will be greater than the sum of ASCII
 * values in s by exactly the ASCII value of the added character.
 *
 * Approach
 * Initialize an accumulator sum to 0
 * Iterate through each character in t, adding its ASCII value to sum
 * Iterate through each character in s, subtracting its ASCII value from sum
 * The remaining value in sum is the ASCII value of the extra character
 * Cast the integer result back to char and return it
 *
 * Complexity
 * Time complexity: O(n), where n is the length of string t (we traverse each string once)
 * Space complexity: O(1), using only a single integer variable for accumulation
 */
